### ISSUE TITLE
Infografía Gestión de Requisitos

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/infografia-Band-hi-1#1]
[Especificacion de Requisitos - Gandhi Salazar Cruz.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Band-hi-1/files/8056853/Especificacion.de.Requisitos.-.Gandhi.Salazar.Cruz.pdf)

**Comment by DuilioAquino10** [comment]
Calificación: 20.

**Comment by josealfredo79** [comment]
Aqui falto lo del estandar

**Comment by josealfredo79** [comment]
Bien hecho y revisado
